// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/script/v1/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/cosmos/gogoproto/types/any"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventUpdateScript is an event emitted when a script is updated.
type EventUpdateScript struct {
	// The new version of the script.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *EventUpdateScript) Reset()         { *m = EventUpdateScript{} }
func (m *EventUpdateScript) String() string { return proto.CompactTextString(m) }
func (*EventUpdateScript) ProtoMessage()    {}
func (*EventUpdateScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_848ca6ed468fa3ce, []int{0}
}
func (m *EventUpdateScript) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventUpdateScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventUpdateScript.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventUpdateScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateScript.Merge(m, src)
}
func (m *EventUpdateScript) XXX_Size() int {
	return m.Size()
}
func (m *EventUpdateScript) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateScript.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateScript proto.InternalMessageInfo

func (m *EventUpdateScript) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

// Event ExecScript is an event emitted when a script is executed.
type EventExecScript struct {
	// The result of the script execution.
	Request  *MsgExec         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response *MsgExecResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	// Executor and target identifiers for indexing
	ExecutorAddress string `protobuf:"bytes,3,opt,name=executor_address,json=executorAddress,proto3" json:"executor_address,omitempty"`
	ScriptAddress   string `protobuf:"bytes,4,opt,name=script_address,json=scriptAddress,proto3" json:"script_address,omitempty"`
	ScriptName      string `protobuf:"bytes,5,opt,name=script_name,json=scriptName,proto3" json:"script_name,omitempty"`
	FunctionName    string `protobuf:"bytes,6,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
}

func (m *EventExecScript) Reset()         { *m = EventExecScript{} }
func (m *EventExecScript) String() string { return proto.CompactTextString(m) }
func (*EventExecScript) ProtoMessage()    {}
func (*EventExecScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_848ca6ed468fa3ce, []int{1}
}
func (m *EventExecScript) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventExecScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventExecScript.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventExecScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventExecScript.Merge(m, src)
}
func (m *EventExecScript) XXX_Size() int {
	return m.Size()
}
func (m *EventExecScript) XXX_DiscardUnknown() {
	xxx_messageInfo_EventExecScript.DiscardUnknown(m)
}

var xxx_messageInfo_EventExecScript proto.InternalMessageInfo

func (m *EventExecScript) GetRequest() *MsgExec {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *EventExecScript) GetResponse() *MsgExecResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *EventExecScript) GetExecutorAddress() string {
	if m != nil {
		return m.ExecutorAddress
	}
	return ""
}

func (m *EventExecScript) GetScriptAddress() string {
	if m != nil {
		return m.ScriptAddress
	}
	return ""
}

func (m *EventExecScript) GetScriptName() string {
	if m != nil {
		return m.ScriptName
	}
	return ""
}

func (m *EventExecScript) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

// EventScriptEvent is an event emitted by the script itself.
type EventScriptEvent struct {
	// Address of the script
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// The key of the event.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the event.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *EventScriptEvent) Reset()         { *m = EventScriptEvent{} }
func (m *EventScriptEvent) String() string { return proto.CompactTextString(m) }
func (*EventScriptEvent) ProtoMessage()    {}
func (*EventScriptEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_848ca6ed468fa3ce, []int{2}
}
func (m *EventScriptEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventScriptEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventScriptEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventScriptEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventScriptEvent.Merge(m, src)
}
func (m *EventScriptEvent) XXX_Size() int {
	return m.Size()
}
func (m *EventScriptEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EventScriptEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EventScriptEvent proto.InternalMessageInfo

func (m *EventScriptEvent) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventScriptEvent) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EventScriptEvent) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// EventCreateNewScript is an event emitted when a new script is created.
type EventCreateNewScript struct {
	// The address of the newly created script.
	ScriptAddress string `protobuf:"bytes,1,opt,name=script_address,json=scriptAddress,proto3" json:"script_address,omitempty"`
	// The address of the creator.
	CreatorAddress string `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	// The initial version of the script.
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *EventCreateNewScript) Reset()         { *m = EventCreateNewScript{} }
func (m *EventCreateNewScript) String() string { return proto.CompactTextString(m) }
func (*EventCreateNewScript) ProtoMessage()    {}
func (*EventCreateNewScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_848ca6ed468fa3ce, []int{3}
}
func (m *EventCreateNewScript) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventCreateNewScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventCreateNewScript.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventCreateNewScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCreateNewScript.Merge(m, src)
}
func (m *EventCreateNewScript) XXX_Size() int {
	return m.Size()
}
func (m *EventCreateNewScript) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCreateNewScript.DiscardUnknown(m)
}

var xxx_messageInfo_EventCreateNewScript proto.InternalMessageInfo

func (m *EventCreateNewScript) GetScriptAddress() string {
	if m != nil {
		return m.ScriptAddress
	}
	return ""
}

func (m *EventCreateNewScript) GetCreatorAddress() string {
	if m != nil {
		return m.CreatorAddress
	}
	return ""
}

func (m *EventCreateNewScript) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*EventUpdateScript)(nil), "dysonprotocol.script.v1.EventUpdateScript")
	proto.RegisterType((*EventExecScript)(nil), "dysonprotocol.script.v1.EventExecScript")
	proto.RegisterType((*EventScriptEvent)(nil), "dysonprotocol.script.v1.EventScriptEvent")
	proto.RegisterType((*EventCreateNewScript)(nil), "dysonprotocol.script.v1.EventCreateNewScript")
}

func init() {
	proto.RegisterFile("dysonprotocol/script/v1/events.proto", fileDescriptor_848ca6ed468fa3ce)
}

var fileDescriptor_848ca6ed468fa3ce = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x4d, 0x3f, 0xe8, 0x94, 0x36, 0xa9, 0x15, 0x09, 0xb7, 0x07, 0x13, 0x05, 0x10,
	0xe1, 0x80, 0xad, 0xc2, 0xad, 0x37, 0x3e, 0x7a, 0xa4, 0x07, 0x03, 0x17, 0x2e, 0x95, 0xeb, 0x4c,
	0xad, 0x88, 0x78, 0xc7, 0xec, 0xae, 0x4d, 0x72, 0xe3, 0x11, 0x78, 0x0f, 0x5e, 0x84, 0x63, 0x8f,
	0x1c, 0x51, 0xf2, 0x22, 0xc8, 0xb3, 0xbb, 0x55, 0x23, 0xa8, 0xb8, 0x44, 0x3b, 0xff, 0xf9, 0xfd,
	0x67, 0x32, 0xe3, 0x81, 0xc7, 0x93, 0x85, 0x26, 0x59, 0x29, 0x32, 0x94, 0xd3, 0x2c, 0xd1, 0xb9,
	0x9a, 0x56, 0x26, 0x69, 0x4e, 0x12, 0x6c, 0x50, 0x1a, 0x1d, 0x73, 0x26, 0x78, 0xb0, 0x46, 0xc5,
	0x96, 0x8a, 0x9b, 0x93, 0xe3, 0xa3, 0x9c, 0x74, 0x49, 0xfa, 0x82, 0x53, 0x89, 0x0d, 0xac, 0xe7,
	0x78, 0x78, 0x57, 0x65, 0x33, 0x77, 0xc4, 0xa0, 0xa0, 0x82, 0xac, 0xb3, 0x7d, 0x39, 0xf5, 0x30,
	0x2b, 0xa7, 0x92, 0x12, 0xfe, 0x75, 0xd2, 0x51, 0x41, 0x54, 0xcc, 0x30, 0xe1, 0xe8, 0xb2, 0xbe,
	0x4a, 0x32, 0xb9, 0xb0, 0xa9, 0xd1, 0x73, 0x38, 0x3c, 0x6b, 0xff, 0xe9, 0xc7, 0x6a, 0x92, 0x19,
	0x7c, 0xcf, 0x4d, 0x82, 0x10, 0x76, 0x1a, 0x54, 0x7a, 0x4a, 0x32, 0x14, 0x43, 0x31, 0xde, 0x4c,
	0x7d, 0x38, 0xfa, 0xb1, 0x01, 0x3d, 0xe6, 0xcf, 0xe6, 0x98, 0x3b, 0xfa, 0x14, 0x76, 0x14, 0x7e,
	0xa9, 0x51, 0x1b, 0xa6, 0xf7, 0x5e, 0x0c, 0xe3, 0x3b, 0xc6, 0x8d, 0xdf, 0xe9, 0xa2, 0x35, 0xa6,
	0xde, 0x10, 0xbc, 0x85, 0x7b, 0x0a, 0x75, 0x45, 0x52, 0x63, 0xb8, 0xc1, 0xe6, 0xf1, 0x7f, 0xcd,
	0x8e, 0x4f, 0x6f, 0x9c, 0xc1, 0x33, 0xe8, 0xe3, 0x1c, 0xf3, 0xda, 0x90, 0xba, 0xc8, 0x26, 0x13,
	0x85, 0x5a, 0x87, 0xdd, 0xa1, 0x18, 0xef, 0xa6, 0x3d, 0xaf, 0xbf, 0xb2, 0x72, 0xf0, 0x04, 0x0e,
	0x6c, 0xc5, 0x1b, 0x70, 0x93, 0xc1, 0x7d, 0xab, 0x7a, 0xec, 0x21, 0xec, 0x39, 0x4c, 0x66, 0x25,
	0x86, 0x5b, 0xcc, 0x80, 0x95, 0xce, 0xb3, 0x12, 0x83, 0x47, 0xb0, 0x7f, 0x55, 0xcb, 0xdc, 0x4c,
	0x49, 0x5a, 0x64, 0x9b, 0x91, 0xfb, 0x5e, 0x6c, 0xa1, 0xd1, 0x07, 0xe8, 0xf3, 0xb2, 0xec, 0xa2,
	0xf8, 0xd9, 0xee, 0xd6, 0x77, 0x16, 0x6c, 0xf1, 0x61, 0xd0, 0x87, 0xee, 0x67, 0x5c, 0xf0, 0x1a,
	0x76, 0xd3, 0xf6, 0x19, 0x0c, 0x60, 0xab, 0xc9, 0x66, 0x35, 0xba, 0x61, 0x6c, 0x30, 0xfa, 0x26,
	0x60, 0xc0, 0xb5, 0xde, 0x28, 0xcc, 0x0c, 0x9e, 0xe3, 0x57, 0xf7, 0x21, 0xfe, 0x9e, 0x4d, 0xfc,
	0x6b, 0xb6, 0xa7, 0xd0, 0xcb, 0x5b, 0xe7, 0xad, 0x65, 0xd9, 0x9e, 0x07, 0x4e, 0xf6, 0xe0, 0xad,
	0x33, 0xe8, 0xae, 0x9d, 0xc1, 0xeb, 0xd3, 0x9f, 0xcb, 0x48, 0x5c, 0x2f, 0x23, 0xf1, 0x7b, 0x19,
	0x89, 0xef, 0xab, 0xa8, 0x73, 0xbd, 0x8a, 0x3a, 0xbf, 0x56, 0x51, 0xe7, 0xd3, 0xfa, 0xd5, 0xc6,
	0x39, 0x95, 0xc9, 0xdc, 0xdf, 0xae, 0x59, 0x54, 0xa8, 0x2f, 0xb7, 0x39, 0xf9, 0xf2, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe0, 0xf5, 0x8e, 0xce, 0x3a, 0x03, 0x00, 0x00,
}

func (m *EventUpdateScript) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventUpdateScript) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventUpdateScript) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventExecScript) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventExecScript) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventExecScript) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FunctionName) > 0 {
		i -= len(m.FunctionName)
		copy(dAtA[i:], m.FunctionName)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.FunctionName)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ScriptName) > 0 {
		i -= len(m.ScriptName)
		copy(dAtA[i:], m.ScriptName)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ScriptName)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ScriptAddress) > 0 {
		i -= len(m.ScriptAddress)
		copy(dAtA[i:], m.ScriptAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ScriptAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ExecutorAddress) > 0 {
		i -= len(m.ExecutorAddress)
		copy(dAtA[i:], m.ExecutorAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ExecutorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Response != nil {
		{
			size, err := m.Response.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Request != nil {
		{
			size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvents(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventScriptEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventScriptEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventScriptEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventCreateNewScript) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventCreateNewScript) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventCreateNewScript) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CreatorAddress) > 0 {
		i -= len(m.CreatorAddress)
		copy(dAtA[i:], m.CreatorAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.CreatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ScriptAddress) > 0 {
		i -= len(m.ScriptAddress)
		copy(dAtA[i:], m.ScriptAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.ScriptAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventUpdateScript) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovEvents(uint64(m.Version))
	}
	return n
}

func (m *EventExecScript) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		l = m.Request.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Response != nil {
		l = m.Response.Size()
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ExecutorAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ScriptAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.ScriptName)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.FunctionName)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventScriptEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventCreateNewScript) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ScriptAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.CreatorAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovEvents(uint64(m.Version))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventUpdateScript) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventUpdateScript: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventUpdateScript: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventExecScript) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventExecScript: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventExecScript: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Request == nil {
				m.Request = &MsgExec{}
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Response == nil {
				m.Response = &MsgExecResponse{}
			}
			if err := m.Response.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FunctionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FunctionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventScriptEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventScriptEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventScriptEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventCreateNewScript) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventCreateNewScript: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventCreateNewScript: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScriptAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScriptAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
