// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/crontask/v1/events.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventTaskCreated is emitted when a new task is created
type EventTaskCreated struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventTaskCreated) Reset()         { *m = EventTaskCreated{} }
func (m *EventTaskCreated) String() string { return proto.CompactTextString(m) }
func (*EventTaskCreated) ProtoMessage()    {}
func (*EventTaskCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{0}
}
func (m *EventTaskCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskCreated.Merge(m, src)
}
func (m *EventTaskCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskCreated proto.InternalMessageInfo

func (m *EventTaskCreated) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskCreated) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// EventTaskPending is emitted when a task transitions to PENDING
type EventTaskPending struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventTaskPending) Reset()         { *m = EventTaskPending{} }
func (m *EventTaskPending) String() string { return proto.CompactTextString(m) }
func (*EventTaskPending) ProtoMessage()    {}
func (*EventTaskPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{1}
}
func (m *EventTaskPending) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskPending.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskPending.Merge(m, src)
}
func (m *EventTaskPending) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskPending) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskPending.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskPending proto.InternalMessageInfo

func (m *EventTaskPending) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskPending) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// EventTaskDeleted is emitted when a task is deleted
type EventTaskDeleted struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventTaskDeleted) Reset()         { *m = EventTaskDeleted{} }
func (m *EventTaskDeleted) String() string { return proto.CompactTextString(m) }
func (*EventTaskDeleted) ProtoMessage()    {}
func (*EventTaskDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{2}
}
func (m *EventTaskDeleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskDeleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskDeleted.Merge(m, src)
}
func (m *EventTaskDeleted) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskDeleted proto.InternalMessageInfo

func (m *EventTaskDeleted) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskDeleted) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// EventTaskExecuted is emitted when a task is executed
type EventTaskExecuted struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Status  string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Success bool   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
}

func (m *EventTaskExecuted) Reset()         { *m = EventTaskExecuted{} }
func (m *EventTaskExecuted) String() string { return proto.CompactTextString(m) }
func (*EventTaskExecuted) ProtoMessage()    {}
func (*EventTaskExecuted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{3}
}
func (m *EventTaskExecuted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskExecuted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskExecuted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskExecuted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskExecuted.Merge(m, src)
}
func (m *EventTaskExecuted) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskExecuted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskExecuted.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskExecuted proto.InternalMessageInfo

func (m *EventTaskExecuted) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskExecuted) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventTaskExecuted) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EventTaskExecuted) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// EventTaskExpired is emitted when a task expires without being executed
type EventTaskExpired struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventTaskExpired) Reset()         { *m = EventTaskExpired{} }
func (m *EventTaskExpired) String() string { return proto.CompactTextString(m) }
func (*EventTaskExpired) ProtoMessage()    {}
func (*EventTaskExpired) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{4}
}
func (m *EventTaskExpired) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskExpired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskExpired.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskExpired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskExpired.Merge(m, src)
}
func (m *EventTaskExpired) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskExpired) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskExpired.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskExpired proto.InternalMessageInfo

func (m *EventTaskExpired) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskExpired) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// EventTaskFailed is emitted when a task finishes with failure
type EventTaskFailed struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *EventTaskFailed) Reset()         { *m = EventTaskFailed{} }
func (m *EventTaskFailed) String() string { return proto.CompactTextString(m) }
func (*EventTaskFailed) ProtoMessage()    {}
func (*EventTaskFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{5}
}
func (m *EventTaskFailed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskFailed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskFailed.Merge(m, src)
}
func (m *EventTaskFailed) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskFailed.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskFailed proto.InternalMessageInfo

func (m *EventTaskFailed) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskFailed) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *EventTaskFailed) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// EventTaskPurged is emitted when a terminal task is removed by retention
// cleanup
type EventTaskPurged struct {
	TaskId  uint64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Creator string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventTaskPurged) Reset()         { *m = EventTaskPurged{} }
func (m *EventTaskPurged) String() string { return proto.CompactTextString(m) }
func (*EventTaskPurged) ProtoMessage()    {}
func (*EventTaskPurged) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{6}
}
func (m *EventTaskPurged) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaskPurged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaskPurged.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaskPurged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaskPurged.Merge(m, src)
}
func (m *EventTaskPurged) XXX_Size() int {
	return m.Size()
}
func (m *EventTaskPurged) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaskPurged.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaskPurged proto.InternalMessageInfo

func (m *EventTaskPurged) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *EventTaskPurged) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EventTaskPurged) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// EventCrontaskMetrics is emitted once per block with last-block metrics
// snapshot
type EventCrontaskMetrics struct {
	// executed totals
	ExecutedTotalGas  uint64       `protobuf:"varint,1,opt,name=executed_total_gas,json=executedTotalGas,proto3" json:"executed_total_gas,omitempty"`
	ExecutedTotalFees []types.Coin `protobuf:"bytes,2,rep,name=executed_total_fees,json=executedTotalFees,proto3" json:"executed_total_fees"`
	ExecutedTaskCount uint64       `protobuf:"varint,3,opt,name=executed_task_count,json=executedTaskCount,proto3" json:"executed_task_count,omitempty"`
	// pending snapshot at BeginBlock
	PendingTaskCount         uint64 `protobuf:"varint,10,opt,name=pending_task_count,json=pendingTaskCount,proto3" json:"pending_task_count,omitempty"`
	PendingGasRequested      uint64 `protobuf:"varint,11,opt,name=pending_gas_requested,json=pendingGasRequested,proto3" json:"pending_gas_requested,omitempty"`
	PendingOldestScheduledTs int64  `protobuf:"varint,12,opt,name=pending_oldest_scheduled_ts,json=pendingOldestScheduledTs,proto3" json:"pending_oldest_scheduled_ts,omitempty"`
	// sum of task_gas_fee across all PENDING tasks at BeginBlock
	PendingTotalGasFees []types.Coin `protobuf:"bytes,13,rep,name=pending_total_gas_fees,json=pendingTotalGasFees,proto3" json:"pending_total_gas_fees"`
}

func (m *EventCrontaskMetrics) Reset()         { *m = EventCrontaskMetrics{} }
func (m *EventCrontaskMetrics) String() string { return proto.CompactTextString(m) }
func (*EventCrontaskMetrics) ProtoMessage()    {}
func (*EventCrontaskMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{7}
}
func (m *EventCrontaskMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventCrontaskMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventCrontaskMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventCrontaskMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCrontaskMetrics.Merge(m, src)
}
func (m *EventCrontaskMetrics) XXX_Size() int {
	return m.Size()
}
func (m *EventCrontaskMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCrontaskMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_EventCrontaskMetrics proto.InternalMessageInfo

func (m *EventCrontaskMetrics) GetExecutedTotalGas() uint64 {
	if m != nil {
		return m.ExecutedTotalGas
	}
	return 0
}

func (m *EventCrontaskMetrics) GetExecutedTotalFees() []types.Coin {
	if m != nil {
		return m.ExecutedTotalFees
	}
	return nil
}

func (m *EventCrontaskMetrics) GetExecutedTaskCount() uint64 {
	if m != nil {
		return m.ExecutedTaskCount
	}
	return 0
}

func (m *EventCrontaskMetrics) GetPendingTaskCount() uint64 {
	if m != nil {
		return m.PendingTaskCount
	}
	return 0
}

func (m *EventCrontaskMetrics) GetPendingGasRequested() uint64 {
	if m != nil {
		return m.PendingGasRequested
	}
	return 0
}

func (m *EventCrontaskMetrics) GetPendingOldestScheduledTs() int64 {
	if m != nil {
		return m.PendingOldestScheduledTs
	}
	return 0
}

func (m *EventCrontaskMetrics) GetPendingTotalGasFees() []types.Coin {
	if m != nil {
		return m.PendingTotalGasFees
	}
	return nil
}

// Emitted when a new event subscription is created
type EventSubscriptionCreated struct {
	SubscriptionId uint64 `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Creator        string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventSubscriptionCreated) Reset()         { *m = EventSubscriptionCreated{} }
func (m *EventSubscriptionCreated) String() string { return proto.CompactTextString(m) }
func (*EventSubscriptionCreated) ProtoMessage()    {}
func (*EventSubscriptionCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{8}
}
func (m *EventSubscriptionCreated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSubscriptionCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSubscriptionCreated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSubscriptionCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSubscriptionCreated.Merge(m, src)
}
func (m *EventSubscriptionCreated) XXX_Size() int {
	return m.Size()
}
func (m *EventSubscriptionCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSubscriptionCreated.DiscardUnknown(m)
}

var xxx_messageInfo_EventSubscriptionCreated proto.InternalMessageInfo

func (m *EventSubscriptionCreated) GetSubscriptionId() uint64 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

func (m *EventSubscriptionCreated) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// Emitted when an event subscription is deleted
type EventSubscriptionDeleted struct {
	SubscriptionId uint64 `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Creator        string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventSubscriptionDeleted) Reset()         { *m = EventSubscriptionDeleted{} }
func (m *EventSubscriptionDeleted) String() string { return proto.CompactTextString(m) }
func (*EventSubscriptionDeleted) ProtoMessage()    {}
func (*EventSubscriptionDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{9}
}
func (m *EventSubscriptionDeleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSubscriptionDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSubscriptionDeleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSubscriptionDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSubscriptionDeleted.Merge(m, src)
}
func (m *EventSubscriptionDeleted) XXX_Size() int {
	return m.Size()
}
func (m *EventSubscriptionDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSubscriptionDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventSubscriptionDeleted proto.InternalMessageInfo

func (m *EventSubscriptionDeleted) GetSubscriptionId() uint64 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

func (m *EventSubscriptionDeleted) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

// Emitted when a subscription is triggered for an event
type EventSubscriptionTriggered struct {
	SubscriptionId uint64 `protobuf:"varint,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Creator        string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *EventSubscriptionTriggered) Reset()         { *m = EventSubscriptionTriggered{} }
func (m *EventSubscriptionTriggered) String() string { return proto.CompactTextString(m) }
func (*EventSubscriptionTriggered) ProtoMessage()    {}
func (*EventSubscriptionTriggered) Descriptor() ([]byte, []int) {
	return fileDescriptor_2af129a4f67b74ad, []int{10}
}
func (m *EventSubscriptionTriggered) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSubscriptionTriggered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSubscriptionTriggered.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSubscriptionTriggered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSubscriptionTriggered.Merge(m, src)
}
func (m *EventSubscriptionTriggered) XXX_Size() int {
	return m.Size()
}
func (m *EventSubscriptionTriggered) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSubscriptionTriggered.DiscardUnknown(m)
}

var xxx_messageInfo_EventSubscriptionTriggered proto.InternalMessageInfo

func (m *EventSubscriptionTriggered) GetSubscriptionId() uint64 {
	if m != nil {
		return m.SubscriptionId
	}
	return 0
}

func (m *EventSubscriptionTriggered) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*EventTaskCreated)(nil), "dysonprotocol.crontask.v1.EventTaskCreated")
	proto.RegisterType((*EventTaskPending)(nil), "dysonprotocol.crontask.v1.EventTaskPending")
	proto.RegisterType((*EventTaskDeleted)(nil), "dysonprotocol.crontask.v1.EventTaskDeleted")
	proto.RegisterType((*EventTaskExecuted)(nil), "dysonprotocol.crontask.v1.EventTaskExecuted")
	proto.RegisterType((*EventTaskExpired)(nil), "dysonprotocol.crontask.v1.EventTaskExpired")
	proto.RegisterType((*EventTaskFailed)(nil), "dysonprotocol.crontask.v1.EventTaskFailed")
	proto.RegisterType((*EventTaskPurged)(nil), "dysonprotocol.crontask.v1.EventTaskPurged")
	proto.RegisterType((*EventCrontaskMetrics)(nil), "dysonprotocol.crontask.v1.EventCrontaskMetrics")
	proto.RegisterType((*EventSubscriptionCreated)(nil), "dysonprotocol.crontask.v1.EventSubscriptionCreated")
	proto.RegisterType((*EventSubscriptionDeleted)(nil), "dysonprotocol.crontask.v1.EventSubscriptionDeleted")
	proto.RegisterType((*EventSubscriptionTriggered)(nil), "dysonprotocol.crontask.v1.EventSubscriptionTriggered")
}

func init() {
	proto.RegisterFile("dysonprotocol/crontask/v1/events.proto", fileDescriptor_2af129a4f67b74ad)
}

var fileDescriptor_2af129a4f67b74ad = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9b, 0xd0, 0xc2, 0x16, 0x68, 0xeb, 0x96, 0xe2, 0x06, 0xc9, 0x44, 0x39, 0x40, 0x0e,
	0x95, 0xad, 0x94, 0x2b, 0x5c, 0x1a, 0xd2, 0x8a, 0x03, 0x6a, 0xe5, 0xe6, 0x54, 0x81, 0xac, 0xcd,
	0x7a, 0x30, 0x56, 0x5d, 0x6f, 0xd8, 0x59, 0x47, 0xe9, 0x5f, 0xf0, 0x41, 0x7c, 0x40, 0x8f, 0x3d,
	0x72, 0x42, 0x28, 0xf9, 0x11, 0xb4, 0xb6, 0x37, 0x71, 0x02, 0x54, 0x28, 0xf4, 0xe6, 0xf1, 0x7b,
	0xf3, 0xf6, 0xed, 0xec, 0xcc, 0x90, 0x17, 0xc1, 0x15, 0xf2, 0x64, 0x20, 0xb8, 0xe4, 0x8c, 0xc7,
	0x2e, 0x13, 0x3c, 0x91, 0x14, 0x2f, 0xdc, 0x61, 0xdb, 0x85, 0x21, 0x24, 0x12, 0x9d, 0x0c, 0x33,
	0xf7, 0xe6, 0x78, 0x8e, 0xe6, 0x39, 0xc3, 0x76, 0xdd, 0x66, 0x1c, 0x2f, 0x39, 0xba, 0x7d, 0x8a,
	0xe0, 0x0e, 0xdb, 0x7d, 0x90, 0xb4, 0xed, 0x32, 0x1e, 0x25, 0x79, 0x6a, 0x7d, 0x27, 0xe4, 0x21,
	0xcf, 0x3e, 0x5d, 0xf5, 0x55, 0xfc, 0xdd, 0xff, 0xfb, 0xc1, 0x98, 0xf6, 0x91, 0x89, 0x68, 0x20,
	0x23, 0x5e, 0x68, 0x34, 0xbb, 0x64, 0xb3, 0xab, 0xec, 0xf4, 0x28, 0x5e, 0x74, 0x04, 0x50, 0x09,
	0x81, 0xf9, 0x94, 0xac, 0xa9, 0x0c, 0x3f, 0x0a, 0x2c, 0xa3, 0x61, 0xb4, 0x6a, 0xde, 0xaa, 0x0a,
	0xdf, 0x05, 0xa6, 0x45, 0xd6, 0x98, 0xe2, 0x70, 0x61, 0xad, 0x34, 0x8c, 0xd6, 0x03, 0x4f, 0x87,
	0x73, 0x32, 0xa7, 0x90, 0x04, 0x51, 0x12, 0xfe, 0xaf, 0xcc, 0x5b, 0x88, 0x61, 0x49, 0x37, 0x23,
	0xb2, 0x35, 0x95, 0xe9, 0x8e, 0x80, 0xa5, 0xcb, 0xe9, 0x98, 0xbb, 0x64, 0x15, 0x25, 0x95, 0x29,
	0x5a, 0xd5, 0x0c, 0x28, 0x22, 0x95, 0x81, 0x29, 0x63, 0x80, 0x68, 0xd5, 0x1a, 0x46, 0xeb, 0xbe,
	0xa7, 0xc3, 0xb9, 0x0b, 0x74, 0x47, 0x83, 0x48, 0x2c, 0x77, 0x81, 0x73, 0xb2, 0x31, 0x95, 0x39,
	0xa2, 0x51, 0xbc, 0x9c, 0xfd, 0x1d, 0x72, 0x0f, 0x84, 0xe0, 0xa2, 0x70, 0x9f, 0x07, 0xcd, 0x0f,
	0x25, 0xed, 0xd3, 0x54, 0x84, 0xb7, 0x69, 0xcf, 0x0a, 0xb0, 0xb2, 0x58, 0x00, 0x7d, 0x66, 0x75,
	0xde, 0xf9, 0xb7, 0x2a, 0xd9, 0xc9, 0xe4, 0x3b, 0x45, 0xdf, 0xbd, 0x07, 0x29, 0x22, 0x86, 0xe6,
	0x3e, 0x31, 0xa1, 0x78, 0x0a, 0x5f, 0x72, 0x49, 0x63, 0x3f, 0xa4, 0x58, 0x1c, 0xb7, 0xa9, 0x91,
	0x9e, 0x02, 0x8e, 0x29, 0x9a, 0x27, 0x64, 0x7b, 0x81, 0xfd, 0x09, 0x40, 0xb9, 0xa8, 0xb6, 0xd6,
	0x0f, 0xf6, 0x9c, 0x7c, 0x30, 0x1c, 0x35, 0x18, 0x4e, 0x31, 0x18, 0x4e, 0x87, 0x47, 0xc9, 0x61,
	0xed, 0xfa, 0xc7, 0xf3, 0x8a, 0xb7, 0x35, 0xa7, 0x77, 0x04, 0x80, 0xa6, 0x53, 0x16, 0x54, 0x77,
	0x65, 0x3c, 0x4d, 0x64, 0xe6, 0xbe, 0x56, 0xe2, 0xab, 0x29, 0x50, 0x80, 0xb2, 0x3b, 0xc8, 0xfb,
	0xb8, 0x4c, 0x27, 0xb9, 0xdd, 0x02, 0x99, 0xb1, 0x0f, 0xc8, 0x13, 0xcd, 0x0e, 0x29, 0xfa, 0x02,
	0xbe, 0xa4, 0x80, 0x12, 0x02, 0x6b, 0x3d, 0x4b, 0xd8, 0x2e, 0xc0, 0x63, 0x8a, 0x9e, 0x86, 0xcc,
	0x37, 0xe4, 0x99, 0xce, 0xe1, 0x71, 0x00, 0x28, 0x7d, 0x64, 0x9f, 0x21, 0x48, 0x63, 0xe5, 0x10,
	0xad, 0x87, 0x0d, 0xa3, 0x55, 0xf5, 0xac, 0x82, 0x72, 0x92, 0x31, 0xce, 0x34, 0xa1, 0x87, 0x66,
	0x8f, 0xec, 0x4e, 0x0d, 0xea, 0x72, 0xe6, 0x45, 0x7a, 0xf4, 0x6f, 0x45, 0xd2, 0xa6, 0x74, 0xcd,
	0x55, 0x99, 0x9a, 0x1f, 0x89, 0x95, 0xbd, 0xde, 0x59, 0x69, 0x53, 0xe8, 0xb5, 0xf0, 0x92, 0x6c,
	0x94, 0x17, 0xc8, 0xac, 0x5b, 0x1e, 0x97, 0x7f, 0xdf, 0xda, 0xd7, 0x7f, 0x92, 0xd7, 0x73, 0x7e,
	0x07, 0xf2, 0x3e, 0xa9, 0xff, 0x26, 0xdf, 0x13, 0x51, 0x18, 0x82, 0xb8, 0x93, 0x03, 0x0e, 0x5f,
	0x5f, 0x8f, 0x6d, 0xe3, 0x66, 0x6c, 0x1b, 0x3f, 0xc7, 0xb6, 0xf1, 0x75, 0x62, 0x57, 0x6e, 0x26,
	0x76, 0xe5, 0xfb, 0xc4, 0xae, 0x9c, 0x37, 0x17, 0xd6, 0x38, 0xbf, 0x74, 0x47, 0xb3, 0xdd, 0x2b,
	0xaf, 0x06, 0x80, 0xfd, 0xd5, 0x0c, 0x7e, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x02, 0x16, 0x26,
	0x38, 0x1b, 0x06, 0x00, 0x00,
}

func (m *EventTaskCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskPending) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskPending) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskPending) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskDeleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskDeleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskDeleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskExecuted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskExecuted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskExecuted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskExpired) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskExpired) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskExpired) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskFailed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskFailed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskFailed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventTaskPurged) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaskPurged) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaskPurged) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x12
	}
	if m.TaskId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.TaskId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventCrontaskMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventCrontaskMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventCrontaskMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PendingTotalGasFees) > 0 {
		for iNdEx := len(m.PendingTotalGasFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingTotalGasFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.PendingOldestScheduledTs != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PendingOldestScheduledTs))
		i--
		dAtA[i] = 0x60
	}
	if m.PendingGasRequested != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PendingGasRequested))
		i--
		dAtA[i] = 0x58
	}
	if m.PendingTaskCount != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PendingTaskCount))
		i--
		dAtA[i] = 0x50
	}
	if m.ExecutedTaskCount != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ExecutedTaskCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ExecutedTotalFees) > 0 {
		for iNdEx := len(m.ExecutedTotalFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExecutedTotalFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.ExecutedTotalGas != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ExecutedTotalGas))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventSubscriptionCreated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSubscriptionCreated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSubscriptionCreated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.SubscriptionId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SubscriptionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventSubscriptionDeleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSubscriptionDeleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSubscriptionDeleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.SubscriptionId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SubscriptionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventSubscriptionTriggered) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSubscriptionTriggered) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSubscriptionTriggered) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.SubscriptionId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.SubscriptionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventTaskCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTaskPending) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTaskDeleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTaskExecuted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Success {
		n += 2
	}
	return n
}

func (m *EventTaskExpired) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTaskFailed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTaskPurged) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TaskId != 0 {
		n += 1 + sovEvents(uint64(m.TaskId))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventCrontaskMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExecutedTotalGas != 0 {
		n += 1 + sovEvents(uint64(m.ExecutedTotalGas))
	}
	if len(m.ExecutedTotalFees) > 0 {
		for _, e := range m.ExecutedTotalFees {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	if m.ExecutedTaskCount != 0 {
		n += 1 + sovEvents(uint64(m.ExecutedTaskCount))
	}
	if m.PendingTaskCount != 0 {
		n += 1 + sovEvents(uint64(m.PendingTaskCount))
	}
	if m.PendingGasRequested != 0 {
		n += 1 + sovEvents(uint64(m.PendingGasRequested))
	}
	if m.PendingOldestScheduledTs != 0 {
		n += 1 + sovEvents(uint64(m.PendingOldestScheduledTs))
	}
	if len(m.PendingTotalGasFees) > 0 {
		for _, e := range m.PendingTotalGasFees {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	return n
}

func (m *EventSubscriptionCreated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubscriptionId != 0 {
		n += 1 + sovEvents(uint64(m.SubscriptionId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventSubscriptionDeleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubscriptionId != 0 {
		n += 1 + sovEvents(uint64(m.SubscriptionId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventSubscriptionTriggered) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubscriptionId != 0 {
		n += 1 + sovEvents(uint64(m.SubscriptionId))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventTaskCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskPending) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskPending: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskPending: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskDeleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskDeleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskDeleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskExecuted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskExecuted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskExecuted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskExpired) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskExpired: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskExpired: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskFailed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskFailed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskFailed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTaskPurged) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaskPurged: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaskPurged: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			m.TaskId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TaskId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventCrontaskMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventCrontaskMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventCrontaskMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedTotalGas", wireType)
			}
			m.ExecutedTotalGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedTotalGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedTotalFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutedTotalFees = append(m.ExecutedTotalFees, types.Coin{})
			if err := m.ExecutedTotalFees[len(m.ExecutedTotalFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedTaskCount", wireType)
			}
			m.ExecutedTaskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedTaskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTaskCount", wireType)
			}
			m.PendingTaskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingTaskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingGasRequested", wireType)
			}
			m.PendingGasRequested = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingGasRequested |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingOldestScheduledTs", wireType)
			}
			m.PendingOldestScheduledTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PendingOldestScheduledTs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTotalGasFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingTotalGasFees = append(m.PendingTotalGasFees, types.Coin{})
			if err := m.PendingTotalGasFees[len(m.PendingTotalGasFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSubscriptionCreated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSubscriptionCreated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSubscriptionCreated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionId", wireType)
			}
			m.SubscriptionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSubscriptionDeleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSubscriptionDeleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSubscriptionDeleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionId", wireType)
			}
			m.SubscriptionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSubscriptionTriggered) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSubscriptionTriggered: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSubscriptionTriggered: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionId", wireType)
			}
			m.SubscriptionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
