// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dysonprotocol/whaleswap/v1/whaleswap.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Pool describes AMM pool state.
//
// Notes:
//   - coin_a.denom < coin_b.denom lexicographically (canonical order)
//   - fee_pct is a decimal string in [0,1)
//   - min_price/max_price are optional decimal strings defining a price band over
//     P = coin_b.amount/coin_a.amount. If unset (or effectively [0, +∞)) the pool
//     behaves as constant-product (v2). If set, concentrated-liquidity math
//     applies.
//   - coin_a.amount/coin_b.amount are sdk.Int strings.
type Pool struct {
	PoolId      uint64     `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinA       types.Coin `protobuf:"bytes,2,opt,name=coin_a,json=coinA,proto3" json:"coin_a"`
	CoinB       types.Coin `protobuf:"bytes,3,opt,name=coin_b,json=coinB,proto3" json:"coin_b"`
	SharesDenom string     `protobuf:"bytes,4,opt,name=shares_denom,json=sharesDenom,proto3" json:"shares_denom,omitempty"`
	// fee_pct is the pool swap fee percentage (cosmos.Dec string in [0,1)).
	FeePct string `protobuf:"bytes,5,opt,name=fee_pct,json=feePct,proto3" json:"fee_pct,omitempty"`
	// min_price/max_price optionally set a price band for concentrated liquidity.
	// Each is expressed as exactly two coins representing the ratio
	// coin_b/coin_a. For example, [{amount: 1, denom: coin_a}, {amount: 2, denom:
	// coin_b}] means min P = 2/1 of coin2 per coin1. Empty means unset.
	MinPrice    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,6,rep,name=min_price,json=minPrice,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"min_price"`
	MaxPrice    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,7,rep,name=max_price,json=maxPrice,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"max_price"`
	BlockHeight uint64                                   `protobuf:"varint,10,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Created     *time.Time                               `protobuf:"bytes,11,opt,name=created,proto3,stdtime" json:"created,omitempty"`
	Updated     *time.Time                               `protobuf:"bytes,12,opt,name=updated,proto3,stdtime" json:"updated,omitempty"`
	NumTrades   uint64                                   `protobuf:"varint,13,opt,name=num_trades,json=numTrades,proto3" json:"num_trades,omitempty"`
	// cumulative swap fees retained by the pool (accrue to LPs)
	FeesEarned github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,14,rep,name=fees_earned,json=feesEarned,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fees_earned"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_774bd74bf1a88692, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *Pool) GetCoinA() types.Coin {
	if m != nil {
		return m.CoinA
	}
	return types.Coin{}
}

func (m *Pool) GetCoinB() types.Coin {
	if m != nil {
		return m.CoinB
	}
	return types.Coin{}
}

func (m *Pool) GetSharesDenom() string {
	if m != nil {
		return m.SharesDenom
	}
	return ""
}

func (m *Pool) GetFeePct() string {
	if m != nil {
		return m.FeePct
	}
	return ""
}

func (m *Pool) GetMinPrice() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MinPrice
	}
	return nil
}

func (m *Pool) GetMaxPrice() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.MaxPrice
	}
	return nil
}

func (m *Pool) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Pool) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Pool) GetUpdated() *time.Time {
	if m != nil {
		return m.Updated
	}
	return nil
}

func (m *Pool) GetNumTrades() uint64 {
	if m != nil {
		return m.NumTrades
	}
	return 0
}

func (m *Pool) GetFeesEarned() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeesEarned
	}
	return nil
}

// OfferData mirrors orderbook offer state.
//
// Status values: "open" | "closed" | "cancelled".
type OfferData struct {
	OfferId          uint64     `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Status           string     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Maker            string     `protobuf:"bytes,3,opt,name=maker,proto3" json:"maker,omitempty"`
	UpdatedHeight    uint64     `protobuf:"varint,4,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
	UpdatedTimestamp *time.Time `protobuf:"bytes,5,opt,name=updated_timestamp,json=updatedTimestamp,proto3,stdtime" json:"updated_timestamp,omitempty"`
	InitialHave      types.Coin `protobuf:"bytes,6,opt,name=initial_have,json=initialHave,proto3" json:"initial_have"`
	InitialWant      types.Coin `protobuf:"bytes,7,opt,name=initial_want,json=initialWant,proto3" json:"initial_want"`
	RemainingHave    types.Coin `protobuf:"bytes,8,opt,name=remaining_have,json=remainingHave,proto3" json:"remaining_have"`
	RemainingWant    types.Coin `protobuf:"bytes,9,opt,name=remaining_want,json=remainingWant,proto3" json:"remaining_want"`
	UnitHaveInt      string     `protobuf:"bytes,10,opt,name=unit_have_int,json=unitHaveInt,proto3" json:"unit_have_int,omitempty"`
	UnitWantInt      string     `protobuf:"bytes,11,opt,name=unit_want_int,json=unitWantInt,proto3" json:"unit_want_int,omitempty"`
	RemainingUnits   string     `protobuf:"bytes,12,opt,name=remaining_units,json=remainingUnits,proto3" json:"remaining_units,omitempty"`
	// pfand_locked is the PFAND coin locked for liquid-mode offers.
	PfandLocked types.Coin `protobuf:"bytes,13,opt,name=pfand_locked,json=pfandLocked,proto3" json:"pfand_locked"`
}

func (m *OfferData) Reset()         { *m = OfferData{} }
func (m *OfferData) String() string { return proto.CompactTextString(m) }
func (*OfferData) ProtoMessage()    {}
func (*OfferData) Descriptor() ([]byte, []int) {
	return fileDescriptor_774bd74bf1a88692, []int{1}
}
func (m *OfferData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OfferData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OfferData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OfferData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferData.Merge(m, src)
}
func (m *OfferData) XXX_Size() int {
	return m.Size()
}
func (m *OfferData) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferData.DiscardUnknown(m)
}

var xxx_messageInfo_OfferData proto.InternalMessageInfo

func (m *OfferData) GetOfferId() uint64 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *OfferData) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OfferData) GetMaker() string {
	if m != nil {
		return m.Maker
	}
	return ""
}

func (m *OfferData) GetUpdatedHeight() uint64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func (m *OfferData) GetUpdatedTimestamp() *time.Time {
	if m != nil {
		return m.UpdatedTimestamp
	}
	return nil
}

func (m *OfferData) GetInitialHave() types.Coin {
	if m != nil {
		return m.InitialHave
	}
	return types.Coin{}
}

func (m *OfferData) GetInitialWant() types.Coin {
	if m != nil {
		return m.InitialWant
	}
	return types.Coin{}
}

func (m *OfferData) GetRemainingHave() types.Coin {
	if m != nil {
		return m.RemainingHave
	}
	return types.Coin{}
}

func (m *OfferData) GetRemainingWant() types.Coin {
	if m != nil {
		return m.RemainingWant
	}
	return types.Coin{}
}

func (m *OfferData) GetUnitHaveInt() string {
	if m != nil {
		return m.UnitHaveInt
	}
	return ""
}

func (m *OfferData) GetUnitWantInt() string {
	if m != nil {
		return m.UnitWantInt
	}
	return ""
}

func (m *OfferData) GetRemainingUnits() string {
	if m != nil {
		return m.RemainingUnits
	}
	return ""
}

func (m *OfferData) GetPfandLocked() types.Coin {
	if m != nil {
		return m.PfandLocked
	}
	return types.Coin{}
}

// Trade captures a single fill of an offer.
type Trade struct {
	TradeId   uint64     `protobuf:"varint,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	OfferId   uint64     `protobuf:"varint,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Taker     string     `protobuf:"bytes,3,opt,name=taker,proto3" json:"taker,omitempty"`
	Height    uint64     `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp *time.Time `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp,omitempty"`
	Sent      types.Coin `protobuf:"bytes,6,opt,name=sent,proto3" json:"sent"`
	Received  types.Coin `protobuf:"bytes,7,opt,name=received,proto3" json:"received"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_774bd74bf1a88692, []int{2}
}
func (m *Trade) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return m.Size()
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetTradeId() uint64 {
	if m != nil {
		return m.TradeId
	}
	return 0
}

func (m *Trade) GetOfferId() uint64 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Trade) GetTaker() string {
	if m != nil {
		return m.Taker
	}
	return ""
}

func (m *Trade) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Trade) GetTimestamp() *time.Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Trade) GetSent() types.Coin {
	if m != nil {
		return m.Sent
	}
	return types.Coin{}
}

func (m *Trade) GetReceived() types.Coin {
	if m != nil {
		return m.Received
	}
	return types.Coin{}
}

// AuctionRecord stores metadata for a whaleswap-created auction escrow.
type AuctionRecord struct {
	AuctionId uint64     `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	ClassId   string     `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	NftId     string     `protobuf:"bytes,3,opt,name=nft_id,json=nftId,proto3" json:"nft_id,omitempty"`
	Sell      types.Coin `protobuf:"bytes,4,opt,name=sell,proto3" json:"sell"`
	BidDenom  string     `protobuf:"bytes,5,opt,name=bid_denom,json=bidDenom,proto3" json:"bid_denom,omitempty"`
	Seller    string     `protobuf:"bytes,6,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (m *AuctionRecord) Reset()         { *m = AuctionRecord{} }
func (m *AuctionRecord) String() string { return proto.CompactTextString(m) }
func (*AuctionRecord) ProtoMessage()    {}
func (*AuctionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_774bd74bf1a88692, []int{3}
}
func (m *AuctionRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuctionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuctionRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuctionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionRecord.Merge(m, src)
}
func (m *AuctionRecord) XXX_Size() int {
	return m.Size()
}
func (m *AuctionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionRecord proto.InternalMessageInfo

func (m *AuctionRecord) GetAuctionId() uint64 {
	if m != nil {
		return m.AuctionId
	}
	return 0
}

func (m *AuctionRecord) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *AuctionRecord) GetNftId() string {
	if m != nil {
		return m.NftId
	}
	return ""
}

func (m *AuctionRecord) GetSell() types.Coin {
	if m != nil {
		return m.Sell
	}
	return types.Coin{}
}

func (m *AuctionRecord) GetBidDenom() string {
	if m != nil {
		return m.BidDenom
	}
	return ""
}

func (m *AuctionRecord) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func init() {
	proto.RegisterType((*Pool)(nil), "dysonprotocol.whaleswap.v1.Pool")
	proto.RegisterType((*OfferData)(nil), "dysonprotocol.whaleswap.v1.OfferData")
	proto.RegisterType((*Trade)(nil), "dysonprotocol.whaleswap.v1.Trade")
	proto.RegisterType((*AuctionRecord)(nil), "dysonprotocol.whaleswap.v1.AuctionRecord")
}

func init() {
	proto.RegisterFile("dysonprotocol/whaleswap/v1/whaleswap.proto", fileDescriptor_774bd74bf1a88692)
}

var fileDescriptor_774bd74bf1a88692 = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x6e, 0xba, 0xf9, 0xf3, 0xa4, 0x29, 0x30, 0x5a, 0xc0, 0x0d, 0x22, 0xed, 0x06, 0xa1, 0xad,
	0x90, 0xea, 0x6c, 0x59, 0x89, 0x0b, 0x10, 0x48, 0x0d, 0x05, 0x6d, 0x24, 0x10, 0x95, 0x59, 0x84,
	0xc4, 0x8d, 0x35, 0xf6, 0x1c, 0x27, 0xa3, 0xda, 0x33, 0x91, 0x67, 0x92, 0x76, 0xdf, 0x62, 0x9f,
	0x83, 0x3b, 0xa4, 0x95, 0x78, 0x85, 0xbd, 0x5c, 0xed, 0x0d, 0x5c, 0xb1, 0xa8, 0xe5, 0x41, 0xd0,
	0x1c, 0x4f, 0x92, 0xe6, 0xa6, 0x72, 0x25, 0xb8, 0x4a, 0xce, 0xcf, 0xf7, 0x9d, 0xe3, 0x33, 0xdf,
	0xf1, 0x98, 0x7c, 0xc2, 0x9f, 0x69, 0x25, 0x67, 0x85, 0x32, 0x2a, 0x51, 0xd9, 0xf0, 0x62, 0xca,
	0x32, 0xd0, 0x17, 0x6c, 0x36, 0x5c, 0x1c, 0xaf, 0x8d, 0x00, 0xe3, 0xb4, 0xb7, 0x91, 0x1b, 0xac,
	0xc3, 0x8b, 0xe3, 0xde, 0xfd, 0x89, 0x9a, 0x28, 0x0c, 0x0d, 0xed, 0xbf, 0x12, 0xd1, 0xdb, 0x9f,
	0x28, 0x35, 0xc9, 0x60, 0x88, 0x56, 0x3c, 0x4f, 0x87, 0x46, 0xe4, 0xa0, 0x0d, 0xcb, 0x1d, 0x65,
	0xaf, 0x9f, 0x28, 0x9d, 0x2b, 0x3d, 0x8c, 0x99, 0x86, 0xe1, 0xe2, 0x38, 0x06, 0xc3, 0x8e, 0x87,
	0x89, 0x12, 0xd2, 0xc5, 0xf7, 0xca, 0x78, 0x54, 0x32, 0x97, 0x46, 0x19, 0x1a, 0xfc, 0xd1, 0x20,
	0xf5, 0x33, 0xa5, 0x32, 0xfa, 0x3e, 0x69, 0xcd, 0x94, 0xca, 0x22, 0xc1, 0xfd, 0xda, 0x41, 0xed,
	0xb0, 0x1e, 0x36, 0xad, 0x39, 0xe6, 0xf4, 0x33, 0xd2, 0xb4, 0x54, 0x11, 0xf3, 0xb7, 0x0f, 0x6a,
	0x87, 0x9d, 0x4f, 0xf7, 0x02, 0x47, 0x60, 0xab, 0x05, 0xae, 0x5a, 0xf0, 0xb5, 0x12, 0x72, 0x54,
	0x7f, 0xf9, 0xd7, 0xfe, 0x56, 0xd8, 0xb0, 0xe9, 0x27, 0x2b, 0x5c, 0xec, 0xdf, 0xbb, 0x03, 0x6e,
	0x44, 0x1f, 0x90, 0x1d, 0x3d, 0x65, 0x05, 0xe8, 0x88, 0x83, 0x54, 0xb9, 0x5f, 0x3f, 0xa8, 0x1d,
	0x7a, 0x61, 0xa7, 0xf4, 0x9d, 0x5a, 0x17, 0x7d, 0x48, 0x5a, 0x29, 0x40, 0x34, 0x4b, 0x8c, 0xdf,
	0xb0, 0xd1, 0xd1, 0xee, 0xeb, 0x17, 0x47, 0xc4, 0xd1, 0x9f, 0x42, 0x12, 0x36, 0x53, 0x80, 0xb3,
	0xc4, 0xd0, 0x29, 0xf1, 0x72, 0x21, 0xa3, 0x59, 0x21, 0x12, 0xf0, 0x9b, 0x07, 0xf7, 0x6e, 0x6f,
	0xe3, 0x91, 0x6d, 0xe3, 0xd7, 0x37, 0xfb, 0x87, 0x13, 0x61, 0xa6, 0xf3, 0x38, 0x48, 0x54, 0xee,
	0x86, 0xe5, 0x7e, 0x8e, 0x34, 0x3f, 0x1f, 0x9a, 0x67, 0x33, 0xd0, 0x08, 0xd0, 0x61, 0x3b, 0x17,
	0xf2, 0xcc, 0x92, 0x63, 0x25, 0x76, 0xe9, 0x2a, 0xb5, 0xfe, 0x8f, 0x4a, 0xec, 0xb2, 0xac, 0xf4,
	0x80, 0xec, 0xc4, 0x99, 0x4a, 0xce, 0xa3, 0x29, 0x88, 0xc9, 0xd4, 0xf8, 0x04, 0x4f, 0xab, 0x83,
	0xbe, 0x27, 0xe8, 0xa2, 0x9f, 0x93, 0x56, 0x52, 0x00, 0x33, 0xc0, 0xfd, 0x0e, 0xce, 0xbe, 0x17,
	0x94, 0x12, 0x0a, 0x96, 0x12, 0x0a, 0x9e, 0x2e, 0x25, 0x34, 0xaa, 0x3f, 0x7f, 0xb3, 0x5f, 0x0b,
	0x97, 0x00, 0x8b, 0x9d, 0xcf, 0x38, 0x62, 0x77, 0xaa, 0x62, 0x1d, 0x80, 0x7e, 0x48, 0x88, 0x9c,
	0xe7, 0x91, 0x29, 0x18, 0x07, 0xed, 0x77, 0xb1, 0x31, 0x4f, 0xce, 0xf3, 0xa7, 0xe8, 0xa0, 0x19,
	0xe9, 0xa4, 0x00, 0x3a, 0x02, 0x56, 0x48, 0xe0, 0xfe, 0xee, 0x7f, 0x3f, 0x25, 0x62, 0xf9, 0xbf,
	0x41, 0xfa, 0xc1, 0x6f, 0x0d, 0xe2, 0xfd, 0x90, 0xa6, 0x50, 0x9c, 0x32, 0xc3, 0xe8, 0x1e, 0x69,
	0x2b, 0x6b, 0xac, 0xf5, 0xdd, 0x42, 0x7b, 0xcc, 0xe9, 0x7b, 0xa4, 0xa9, 0x0d, 0x33, 0x73, 0x8d,
	0x02, 0xf7, 0x42, 0x67, 0xd1, 0x80, 0x34, 0x72, 0x76, 0x0e, 0x05, 0xea, 0xd7, 0x1b, 0xf9, 0xaf,
	0x5f, 0x1c, 0xdd, 0x77, 0xbd, 0x9e, 0x70, 0x5e, 0x80, 0xd6, 0x3f, 0x9a, 0x42, 0xc8, 0x49, 0x58,
	0xa6, 0xd1, 0x8f, 0xc9, 0xae, 0x1b, 0xc4, 0xf2, 0x68, 0xea, 0x58, 0xa8, 0xeb, 0xbc, 0xee, 0x70,
	0xbe, 0x27, 0xef, 0x2c, 0xd3, 0x56, 0x7b, 0x8c, 0x32, 0xae, 0x32, 0xea, 0xb7, 0x1d, 0x74, 0xe5,
	0xa7, 0x23, 0xb2, 0x23, 0xa4, 0x30, 0x82, 0x65, 0xd1, 0x94, 0x2d, 0xac, 0xca, 0x2b, 0x2d, 0x5b,
	0xc7, 0x81, 0x9e, 0xb0, 0x05, 0xdc, 0xe4, 0xb8, 0x60, 0xd2, 0xf8, 0xad, 0xbb, 0x71, 0xfc, 0xcc,
	0xa4, 0xa1, 0xdf, 0x92, 0xdd, 0x02, 0x72, 0x26, 0xa4, 0x90, 0x93, 0xb2, 0x93, 0x76, 0x35, 0x96,
	0xee, 0x0a, 0x86, 0xbd, 0x6c, 0xf0, 0x60, 0x37, 0xde, 0x5d, 0x79, 0xb0, 0x9f, 0x01, 0xe9, 0xce,
	0xa5, 0x30, 0xd8, 0x4a, 0x24, 0x64, 0xb9, 0x27, 0x5e, 0xd8, 0xb1, 0x4e, 0x5b, 0x68, 0x7c, 0x23,
	0xc7, 0x96, 0xc1, 0x9c, 0xce, 0x3a, 0xc7, 0x92, 0xd8, 0x9c, 0x87, 0xe4, 0xad, 0x75, 0x3f, 0x36,
	0xa0, 0x71, 0x2f, 0xbc, 0x70, 0xdd, 0xe6, 0x4f, 0xd6, 0x6b, 0x87, 0x38, 0x4b, 0x99, 0xe4, 0x91,
	0x5d, 0x44, 0xe0, 0x28, 0xff, 0x2a, 0x43, 0x44, 0xd0, 0x77, 0x88, 0x19, 0xfc, 0xbe, 0x4d, 0x1a,
	0xb8, 0x2c, 0x56, 0xaf, 0xb8, 0x46, 0x37, 0xf4, 0x8a, 0xf6, 0x98, 0x6f, 0x48, 0x79, 0x7b, 0x53,
	0xca, 0x01, 0x69, 0x98, 0x6a, 0x92, 0xc5, 0x34, 0x2b, 0xfd, 0x0d, 0xa9, 0x3a, 0x8b, 0x7e, 0x45,
	0xbc, 0xbb, 0x6b, 0x73, 0x0d, 0xa1, 0x8f, 0x49, 0x5d, 0x83, 0x34, 0x55, 0xc5, 0x88, 0xc9, 0xf4,
	0x0b, 0xd2, 0x2e, 0x20, 0x01, 0xb1, 0x00, 0x5e, 0x55, 0x81, 0x2b, 0xc0, 0xe0, 0x9f, 0x1a, 0xe9,
	0x9e, 0xcc, 0x13, 0x23, 0x94, 0x0c, 0x21, 0x51, 0x05, 0xbe, 0x8c, 0x58, 0xe9, 0x58, 0xcf, 0xd0,
	0x73, 0x9e, 0x72, 0x8a, 0x49, 0xc6, 0xb4, 0x5e, 0x4e, 0xd1, 0x0b, 0x5b, 0x68, 0x8f, 0x39, 0x7d,
	0x97, 0x34, 0x65, 0x6a, 0x6c, 0x00, 0xc7, 0x18, 0x36, 0x64, 0x6a, 0xc6, 0xbc, 0x7c, 0xa8, 0x2c,
	0xc3, 0x51, 0x55, 0x7b, 0xa8, 0x2c, 0xa3, 0x1f, 0x10, 0x2f, 0x16, 0xdc, 0x5d, 0x65, 0x78, 0x59,
	0x85, 0xed, 0x58, 0xf0, 0xf2, 0x1e, 0x7b, 0x44, 0x9a, 0x36, 0x09, 0x0a, 0x1c, 0xd4, 0x6d, 0xe7,
	0xe5, 0xf2, 0x46, 0x5f, 0xbe, 0xbc, 0xea, 0xd7, 0x5e, 0x5d, 0xf5, 0x6b, 0x7f, 0x5f, 0xf5, 0x6b,
	0xcf, 0xaf, 0xfb, 0x5b, 0xaf, 0xae, 0xfb, 0x5b, 0x7f, 0x5e, 0xf7, 0xb7, 0x7e, 0xf9, 0x68, 0xf3,
	0xb3, 0xc2, 0xbe, 0x2b, 0x2f, 0x6f, 0x7c, 0x88, 0xe0, 0x5b, 0x32, 0x6e, 0x62, 0xfc, 0xf1, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x63, 0xc7, 0xd7, 0xb0, 0x08, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeesEarned) > 0 {
		for iNdEx := len(m.FeesEarned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeesEarned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWhaleswap(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if m.NumTrades != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.NumTrades))
		i--
		dAtA[i] = 0x68
	}
	if m.Updated != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Updated, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Updated):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintWhaleswap(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x62
	}
	if m.Created != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Created, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintWhaleswap(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x5a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x50
	}
	if len(m.MaxPrice) > 0 {
		for iNdEx := len(m.MaxPrice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MaxPrice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWhaleswap(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.MinPrice) > 0 {
		for iNdEx := len(m.MinPrice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinPrice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWhaleswap(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.FeePct) > 0 {
		i -= len(m.FeePct)
		copy(dAtA[i:], m.FeePct)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.FeePct)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SharesDenom) > 0 {
		i -= len(m.SharesDenom)
		copy(dAtA[i:], m.SharesDenom)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.SharesDenom)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.CoinB.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.CoinA.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.PoolId != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OfferData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OfferData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OfferData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.PfandLocked.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if len(m.RemainingUnits) > 0 {
		i -= len(m.RemainingUnits)
		copy(dAtA[i:], m.RemainingUnits)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.RemainingUnits)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.UnitWantInt) > 0 {
		i -= len(m.UnitWantInt)
		copy(dAtA[i:], m.UnitWantInt)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.UnitWantInt)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.UnitHaveInt) > 0 {
		i -= len(m.UnitHaveInt)
		copy(dAtA[i:], m.UnitHaveInt)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.UnitHaveInt)))
		i--
		dAtA[i] = 0x52
	}
	{
		size, err := m.RemainingWant.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.RemainingHave.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size, err := m.InitialWant.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.InitialHave.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.UpdatedTimestamp != nil {
		n10, err10 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UpdatedTimestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTimestamp):])
		if err10 != nil {
			return 0, err10
		}
		i -= n10
		i = encodeVarintWhaleswap(dAtA, i, uint64(n10))
		i--
		dAtA[i] = 0x2a
	}
	if m.UpdatedHeight != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Maker) > 0 {
		i -= len(m.Maker)
		copy(dAtA[i:], m.Maker)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.Maker)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x12
	}
	if m.OfferId != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.OfferId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Trade) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Trade) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Trade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Received.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Sent.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Timestamp != nil {
		n13, err13 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Timestamp):])
		if err13 != nil {
			return 0, err13
		}
		i -= n13
		i = encodeVarintWhaleswap(dAtA, i, uint64(n13))
		i--
		dAtA[i] = 0x2a
	}
	if m.Height != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Taker) > 0 {
		i -= len(m.Taker)
		copy(dAtA[i:], m.Taker)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.Taker)))
		i--
		dAtA[i] = 0x1a
	}
	if m.OfferId != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.OfferId))
		i--
		dAtA[i] = 0x10
	}
	if m.TradeId != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.TradeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AuctionRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuctionRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuctionRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BidDenom) > 0 {
		i -= len(m.BidDenom)
		copy(dAtA[i:], m.BidDenom)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.BidDenom)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.Sell.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWhaleswap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.NftId) > 0 {
		i -= len(m.NftId)
		copy(dAtA[i:], m.NftId)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.NftId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintWhaleswap(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0x12
	}
	if m.AuctionId != 0 {
		i = encodeVarintWhaleswap(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWhaleswap(dAtA []byte, offset int, v uint64) int {
	offset -= sovWhaleswap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovWhaleswap(uint64(m.PoolId))
	}
	l = m.CoinA.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = m.CoinB.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = len(m.SharesDenom)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.FeePct)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	if len(m.MinPrice) > 0 {
		for _, e := range m.MinPrice {
			l = e.Size()
			n += 1 + l + sovWhaleswap(uint64(l))
		}
	}
	if len(m.MaxPrice) > 0 {
		for _, e := range m.MaxPrice {
			l = e.Size()
			n += 1 + l + sovWhaleswap(uint64(l))
		}
	}
	if m.BlockHeight != 0 {
		n += 1 + sovWhaleswap(uint64(m.BlockHeight))
	}
	if m.Created != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created)
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	if m.Updated != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Updated)
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	if m.NumTrades != 0 {
		n += 1 + sovWhaleswap(uint64(m.NumTrades))
	}
	if len(m.FeesEarned) > 0 {
		for _, e := range m.FeesEarned {
			l = e.Size()
			n += 1 + l + sovWhaleswap(uint64(l))
		}
	}
	return n
}

func (m *OfferData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OfferId != 0 {
		n += 1 + sovWhaleswap(uint64(m.OfferId))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.Maker)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovWhaleswap(uint64(m.UpdatedHeight))
	}
	if m.UpdatedTimestamp != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UpdatedTimestamp)
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = m.InitialHave.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = m.InitialWant.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = m.RemainingHave.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = m.RemainingWant.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = len(m.UnitHaveInt)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.UnitWantInt)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.RemainingUnits)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = m.PfandLocked.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	return n
}

func (m *Trade) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TradeId != 0 {
		n += 1 + sovWhaleswap(uint64(m.TradeId))
	}
	if m.OfferId != 0 {
		n += 1 + sovWhaleswap(uint64(m.OfferId))
	}
	l = len(m.Taker)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovWhaleswap(uint64(m.Height))
	}
	if m.Timestamp != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Timestamp)
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = m.Sent.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = m.Received.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	return n
}

func (m *AuctionRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AuctionId != 0 {
		n += 1 + sovWhaleswap(uint64(m.AuctionId))
	}
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.NftId)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = m.Sell.Size()
	n += 1 + l + sovWhaleswap(uint64(l))
	l = len(m.BidDenom)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovWhaleswap(uint64(l))
	}
	return n
}

func sovWhaleswap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWhaleswap(x uint64) (n int) {
	return sovWhaleswap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWhaleswap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinA", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinA.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinB", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinB.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharesDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SharesDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePct", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePct = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinPrice = append(m.MinPrice, types.Coin{})
			if err := m.MinPrice[len(m.MinPrice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxPrice = append(m.MaxPrice, types.Coin{})
			if err := m.MaxPrice[len(m.MaxPrice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Created == nil {
				m.Created = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Updated", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Updated == nil {
				m.Updated = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Updated, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumTrades", wireType)
			}
			m.NumTrades = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumTrades |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesEarned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeesEarned = append(m.FeesEarned, types.Coin{})
			if err := m.FeesEarned[len(m.FeesEarned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWhaleswap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OfferData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWhaleswap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OfferData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OfferData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferId", wireType)
			}
			m.OfferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OfferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UpdatedTimestamp == nil {
				m.UpdatedTimestamp = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UpdatedTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialHave", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialHave.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialWant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialWant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingHave", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingHave.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingWant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RemainingWant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnitHaveInt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnitHaveInt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnitWantInt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnitWantInt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingUnits", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemainingUnits = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PfandLocked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PfandLocked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWhaleswap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Trade) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWhaleswap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Trade: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Trade: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradeId", wireType)
			}
			m.TradeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TradeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfferId", wireType)
			}
			m.OfferId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OfferId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Received", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Received.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWhaleswap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuctionRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWhaleswap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuctionRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuctionRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sell", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sell.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BidDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWhaleswap
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWhaleswap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWhaleswap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWhaleswap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWhaleswap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWhaleswap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWhaleswap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWhaleswap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWhaleswap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWhaleswap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWhaleswap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWhaleswap = fmt.Errorf("proto: unexpected end of group")
)
